# Generated by Django 3.0.5 on 2020-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_order_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='icecreamprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.IntegerField()),
            ],
        ),
    ]
