# Generated by Django 3.0.5 on 2020-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200423_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_id', models.IntegerField()),
                ('icecream', models.CharField(max_length=200)),
                ('icecream_img', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='icecreamprices',
        ),
    ]
