# Generated by Django 3.0.5 on 2020-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200424_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='our_collection',
            name='icecream_img',
            field=models.FileField(upload_to=''),
        ),
    ]
