# Generated by Django 3.0.5 on 2020-04-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200427_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_customer',
            old_name='email',
            new_name='username',
        ),
    ]
