# Generated by Django 3.0.5 on 2020-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200427_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_item', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
                ('distt', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=12)),
            ],
        ),
    ]
