# Generated by Django 3.0.5 on 2020-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_cart',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cart_item', models.CharField(max_length=200)),
            ],
        ),
    ]
