# Generated by Django 3.0.5 on 2020-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_cart',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('icecream_id', models.IntegerField()),
                ('icecream_name', models.CharField(max_length=200)),
                ('icecream_image', models.FileField(max_length=200, upload_to='')),
                ('icecream_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='order_cart',
        ),
    ]
