# Generated by Django 3.0.5 on 2020-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200506_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders_cart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
