# Generated by Django 3.0.5 on 2020-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200508_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_updates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update_percentage', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='order_update',
        ),
    ]
