# Generated by Django 3.0.5 on 2020-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200603_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_updates',
            name='update_percentage',
            field=models.IntegerField(max_length=200),
        ),
    ]
