# Generated by Django 3.0.5 on 2020-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20200603_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_updates',
            name='timestamp',
        ),
    ]
