# Generated by Django 3.0.5 on 2020-06-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_order_updates_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_updates',
            name='update_percentage',
        ),
    ]
