# Generated by Django 3.0.5 on 2020-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_remove_order_updates_update_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_updates',
            name='update_percentage',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
