# Generated by Django 3.0.5 on 2021-03-23 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_order_updates_update_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_cart',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_updates',
            name='update_percentage',
            field=models.IntegerField(),
        ),
    ]
