# Generated by Django 3.0.5 on 2021-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20210323_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_customer',
            name='firstname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
